name: pacman-contribution-graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: matchai/pacman-contribution-graph@v3
        with:
          github_user_name: JoaoOliveira07
          github_token: ${{ secrets.GITHUB_TOKEN }}
          days: 365
